title: INTERPOL Darknet and Cryptocurrencies Taxonomy
email: contact@ikna.io
description: >-
  A taxonomy of concepts related to the Darknet and Virtual Assets.
url: "https://ikna.io"
baseurl: "/DW-VA-Taxonomy"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compact # possible values: nested expanded compact compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
